monitor.alsa.rules = [
  {
    matches = [
      {
        "device.name": "~alsa_card.usb-Sony_Interactive_Entertainment_DualSense.*Wireless_Controller.*"
      }
    ]
    actions = {
      "update-props": {
        "device.description": "DualSense Wireless Controller"
        "device.nick": "DualSense"
      }
    }
  }
  {
    matches = [
      {
        "node.name": "~alsa_output.usb-Sony_Interactive_Entertainment_DualSense.*Wireless_Controller.*"
      }
    ]
    actions = {
      "update-props": {
        "node.description": "Wireless Controller"
        "node.nick": "Wireless Controller"
        "audio.channels": 4
        "audio.position": [ "FL", "FR", "RL", "RR" ]
        "channelmix.normalize": false
        "node.pause-on-idle": false
        "session.suspend-timeout-seconds": 0
        "priority.session": 100
        "priority.driver": 100
      }
    }
  }
  {
    matches = [
      {
        "node.name": "~alsa_input.usb-Sony_Interactive_Entertainment_DualSense.*Wireless_Controller.*"
      }
    ]
    actions = {
      "update-props": {
        "node.description": "Wireless Controller Mic"
        "node.nick": "Wireless Controller Mic"
        # vDS does not support microphone input yet. Disable this source because
        # capture traffic can disrupt the controller speaker and haptics output.
        "node.disabled": true
        "priority.session": 1
        "priority.driver": 1
        "session.suspend-timeout-seconds": 0
      }
    }
  }
]
