PACKAGE_NAME="vds_hcd"
PACKAGE_VERSION="unknown"
BUILT_MODULE_NAME[0]="vds_hcd"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
MAKE[0]="make VDS_VERSION=${PACKAGE_VERSION}"
